# Generated by Django 6.0.4 on 2026-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbero', models.CharField(choices=[('Rafael', 'Rafael'), ('Antonio', 'Antonio'), ('Benito', 'Benito'), ('SinCita', 'Sin Cita')], max_length=50)),
                ('servicio', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta')], max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
