# Generated by Django 6.0.4 on 2026-04-18 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(help_text='Para notificaciones de WhatsApp', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.barbero'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=15)),
                ('servicio_solicitado', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente (Agendada por WhatsApp)'), ('L', 'Llegó al local (En espera)'), ('C', 'Completada / Pagada'), ('N', 'No asistió')], default='P', max_length=1)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.barbero')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cita'),
        ),
    ]
