# Generated by Django 6.0.4 on 2026-04-21 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_barbero_alter_venta_barbero_cita_venta_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBarberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(default='Barbería JhonnyBoy', max_length=100)),
                ('hora_apertura', models.TimeField(default='10:00')),
                ('hora_cierre', models.TimeField(default='20:00')),
                ('mensaje_bienvenida', models.TextField(default='¡Hola! Bienvenido a JhonnyBoy. ¿Con quién te gustaría agendar?')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duracion_minutos', models.IntegerField(default=30, help_text='Cuanto tarda el corte aprox')),
                ('descripcion', models.TextField(blank=True, help_text='Ej: Incluye lavado y delineado de barba')),
            ],
        ),
        migrations.AlterModelOptions(
            name='barbero',
            options={'verbose_name_plural': 'Barberos'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='servicio',
        ),
        migrations.AddField(
            model_name='barbero',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Desmarcar si el barbero ya no trabaja aquí'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='servicio_manual',
            field=models.CharField(blank=True, help_text='Solo si no hubo cita previa', max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ventas.barbero'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('barbero', 'fecha_hora')},
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio_solicitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.servicio'),
        ),
    ]
